swagger: 2
info:
  title: 'cen-mc-rc stream API'
  description: 'Interaction between Machine Control and Reading Coding System - [CEN/TS 16238](https://sharepoint-my.sp.swisspost.com/sites/RPZrealisierung/Freigegebene%20Dokumente/20_GesamtRPZ/50_Informatik/15_AT-Gateway/02_Spezifikation%20AT-Gateway/Schnittstellen/CEN_TS/MC_RC/TS_16238_EN.pdf).'
  contact:
    name: 'Kay Herzam (Swiss Post)'
    email: kay.herzam@post.ch
  version: 3.1.0
host: 'server:8080'
basePath: mqtt
paths:
  'cen-mc-rc/v1/machine/submit-mailpiece/{srcSystem}/{srcInstance}':
    post:
      summary: 'ATG-3 Submit Mailpiece (Sensordaten empfangen)'
      description: 'The Machine submits the recognized mailpiece attributes.'
      tags:
        - machine
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ASL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
      responses:
        default:
          schema: {$ref: '#/definitions/SubmitMailpiece'}
  'cen-mc-rc/v1/machinePAR/submit-mailpiece/{srcSystem}/{srcInstance}':
    post:
      summary: 'ATG-3 Submit Mailpiece (Sensordaten empfangen)'
      description: 'PAR submits the recognized mailpiece attributes. [DEPRECATED] Topic will be removed in future releases after WESort is rolled out in all sorting centers.'
      tags:
        - machinePAR
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ASL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
      responses:
        default:
          schema: {$ref: '#/definitions/SubmitMailpiecePAR'}
  'cen-mc-rc/v1/machine/request-mailpiece-attributes/{srcSystem}/{srcInstance}/{conversationId}':
    post:
      summary: 'ATG-4 Request Mailpiece Attributes (Sortierziel berechnen)'
      description: 'Request for the coding result (outlet group)'
      tags:
        - machine
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ASL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
        -
          name: conversationId
          in: path
          description: 'ID that will be included in the transmit-mailpiece-attributes topic in order to correlate the messages'
          type: string
          default: '12345'
      responses:
        default:
          schema: {$ref: '#/definitions/RequestMailpieceAttributes'}
  'cen-mc-rc/v1/machine/update-mailpiece-attributes/{srcSystem}/{srcInstance}':
    post:
      summary: 'ATG-5 Update Mailpiece Attributes (Sortierergebnis empfangen)'
      description: 'The Machine reports new or changed attributes in order to update the mailpiece attribute database on the Coding System (e.g. indicating the sort bin). (Re-)Connected to ATG - The publisher needs to buffer all unsent messages for at least 1 day until the message is sent successfully to the ATG.'
      tags:
        - machine
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ASL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
      responses:
        default:
          schema: {$ref: '#/definitions/UpdateMailpieceAttributes'}
  'cen-mc-rc/v1/machineMail/update-mailpiece-attributes/{srcSystem}/{srcInstance}':
    post:
      summary: 'ATG-5 Update Mailpiece Attributes (Sortierergebnis empfangen)'
      description: 'Extends the standard message for flat sorting by adding attributes to generate the mail sorting event for the run statistics. [DEPRECATED] Topic will be removed in future releases after WESort is able to code and sort flats'
      tags:
        - machineMail
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ASL
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
      responses:
        default:
          schema: {$ref: '#/definitions/UpdateMailpieceAttributesMail'}
  'cen-mc-rc/v1/coding/transmit-mailpiece-attributes/{srcSystem}/{srcInstance}/{dstSystem}/{dstInstance}/{conversationId}':
    post:
      summary: 'ATG-4 Transmit Mailpiece Attributes (Sortierziel berechnen)'
      description: 'The RC System returns mailpiece attributes to the Machine, either in response to a Submit Mailpiece or a Request Mailpiece Attributes. There may be multiple responses of Transmit Mailpiece Attributes for a single “Submit Mailpiece” message, e.g. partial OCR results followed with final VCS result.'
      tags:
        - coding
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ZDS
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
        -
          name: dstSystem
          in: path
          description: '3-letter uppercase name identifying the system receiving the message'
          type: string
          default: ASL
        -
          name: dstInstance
          in: path
          description: 'two-digit padded number identifying the system instance receiving the message'
          type: string
          default: '01'
        -
          name: conversationId
          in: path
          description: 'ID from the request-mailpiece-attributes request for correlation'
          type: string
          default: '12345'
      responses:
        default:
          schema: {$ref: '#/definitions/TransmitMailpieceAttributes'}
  'cen-mc-rc/v1/coding/transmit-mailpiece-attributes/{srcSystem}/{srcInstance}':
    post:
      summary: 'ATG-4 Transmit Mailpiece Attributes (Sortierziel berechnen)'
      description: 'Trigger transmit-mailpiece-attributes event without request (no dstSystem and dstInstance parameters)'
      tags:
        - coding
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ZDS
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
      responses:
        default:
          schema: {$ref: '#/definitions/TransmitMailpieceAttributes'}
  'cen-mc-rc/v1/codingMail/transmit-mailpiece-attributes/{srcSystem}/{srcInstance}/{dstSystem}/{dstInstance}/{conversationId}':
    post:
      summary: 'ATG-4 Transmit Mailpiece Attributes (Sortierziel berechnen)'
      description: 'Extends the standard message for flat sorting by adding coding result attributes to derive the sorting product and outlet group of the mail item. [DEPRECATED] Topic will be removed in future releases after WESort is able to code and sort flats'
      tags:
        - codingMail
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ZDS
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
        -
          name: dstSystem
          in: path
          description: '3-letter uppercase name identifying the system receiving the message'
          type: string
          default: ASL
        -
          name: dstInstance
          in: path
          description: 'two-digit padded number identifying the system instance receiving the message'
          type: string
          default: '01'
        -
          name: conversationId
          in: path
          description: 'ID from the request-mailpiece-attributes request for correlation'
          type: string
          default: '12345'
      responses:
        default:
          schema: {$ref: '#/definitions/TransmitMailpieceAttributesMail'}
  'cen-mc-rc/v1/codingMail/transmit-mailpiece-attributes/{srcSystem}/{srcInstance}':
    post:
      summary: 'ATG-4 Transmit Mailpiece Attributes (Sortierziel berechnen)'
      description: 'Trigger transmit-mailpiece-attributes event without request (no dstSystem and dstInstance parameters). [DEPRECATED] Topic will be removed in future releases after WESort is able to code and sort flats'
      tags:
        - codingMail
      parameters:
        -
          name: srcSystem
          in: path
          description: '3-letter uppercase name identifying the system issuing the message'
          type: string
          default: ZDS
        -
          name: srcInstance
          in: path
          description: 'two-digit padded number identifying the system instance issuing the message'
          type: string
          default: '01'
      responses:
        default:
          schema: {$ref: '#/definitions/TransmitMailpieceAttributesMail'}
definitions:
  $ref:
    - ../ts/submit_mailpiece.ts
    - ../ts/submit_mailpiece_par.ts
    - ../ts/request-mailpiece-attributes.ts
    - ../ts/update_mailpiece_attributes.ts
    - ../ts/update_mailpiece_attributes_mail.ts
    - ../ts/transmit-mailpiece-attributes.ts
    - ../ts/transmit-mailpiece-attributes-mail.ts
